# Generated by Django 4.2.6 on 2024-03-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
